- name: Set Hostname
  ansible.builtin.shell: set-hostname rabbitmq

- name: Configure YUM Repos for RabbitMQ
  ansible.builtin.shell: curl {{item}} | bash
  loop:
    - https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
    - https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh

- name: Install RabbitMQ
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Add Roboshop App User
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('aws_ssm', 'robo-rabbitmq-user', region='us-east-1' ) }}"
    password: "{{ lookup('aws_ssm', 'robo-rabbitmq-pass', region='us-east-1' ) }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
