- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Include app-preclean
  ansible.builtin.import_tasks:
    file: app-pre-clean.yml

- name: Include app-download
  ansible.builtin.import_tasks:
    file: app-download.yml