- name: Install maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: Include app pre-requisite
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Install maven Dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: Start the {{component}} service
  ansible.builtin.import_tasks:
    file: systemd.yml

- name: Load Schema
  ansible.builtin.import_tasks:
    file: schema.yml
  when: is_schema_needed

- name: Restart {{component}} service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: yes