- name: Disable Nodejs default version
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Include app pre-requisite
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Install NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Start the {{component}} service
  ansible.builtin.import_tasks:
    file: systemd.yml

- name: Load Schema
  ansible.builtin.import_tasks:
    file: schema.yml