- name: Block for Mongo Schema
  when: schema_type == "mongodb"
  block:
    - name: Copy mongo repo file
      ansible.builtin.template:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install Mongo Client
      ansible.builtin.dnf:
        name: mongodb-org-shell
        state: installed

    - name: Load Mongo Schema
      ansible.builtin.shell: mongo --host "{{ lookup('aws_ssm', 'robo-{{component}}-mongo-ip', region='us-east-1' ) }}" </app/schema/{{component}}.js


- name: Block for Mysql Schema
  when: schema_type == "mysql"
  block:
    - name: Install mysql client
      ansible.builtin.dnf:
        name: mysql
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', 'robo-mysql-db-host', region='us-east-1' ) }} -u{{ lookup('aws_ssm', 'robo-mysql-db-user', region='us-east-1' ) }} -p{{ lookup('aws_ssm', 'robo-mysql-db-pass', region='us-east-1' ) }} < /app/schema/{{component}}.sql


